<?php

namespace Database\Seeders;

use App\Models\CollegeOffice;
use Illuminate\Database\Seeder;

class CollegeOfficeSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->collegeOffices() as $collegeOfficeName => $departmentNames) {
            $collegeOffice = CollegeOffice::firstOrCreate([
                'name' => trim($collegeOfficeName),
            ]);

            foreach ($departmentNames as $departmentName) {
                $collegeOffice->departments()->firstOrCreate([
                    'name' => trim($departmentName),
                ]);
            }
        }
    }

    private function collegeOffices(): array
    {
        return [
            'ACCOUNTING UNIT' => ['MAIN'],
            'AGRI-HERITAGE-ECO (AHE) TOURISM OFFICE' => ['MAIN'],
            'AGRICULTURAL EXPERIMENT CENTER' => ['MAIN', 'MAT NCT RICE'],
            'BIDS AND AWARD COMMITTEE' => ['MAIN'],
            'BUDGET OFFICE' => ['ACCOUNT 1', 'GENERAL FUND', 'HEAD', 'HOMESTAY', 'MAIN', 'RGMO', 'STF'],
            'CAPABILITY BUILDING UNIT (CBU)-EXTENSION' => ['MAIN'],
            'CARDEC@CMU' => ['MAIN'],
            'CAS EXTENSION COORDINATOR' => ['MAIN'],
            "CASHIER'S UNIT" => ['MAIN'],
            'CENTER FOR BIODIVERSITY RESEARCH AND EXTENSION IN MINDANAO (CEBREM)' => [
                'CHED-DARE-TO-MARILOG',
                'DEPARTMENT OF AGRICULTURE (DA) - BUREAU OF AGRICULTURAL RESEARCH (BAR)',
                'DEPARTMENT OF SCIENCE AND TECHNOLOGY (DOST) - GRANT IN AID (GIA)',
                'DEPARTMENT OF SCIENCE AND TECHNOLOGY (DOST) - NATIONAL RESEARCH COUNCIL OF THE PHILIPPINES (NRCP)',
                'MAIN',
            ],
            'CENTER FOR GENDER AND DEVELOPMENT' => ['MAIN'],
            'CENTRAL MINDANAO UNIVERSITY PRESS' => ['MAIN'],
            'CMU JOURNAL OF SCIENCE' => ['MAIN'],
            'CMU TOURISM' => ['MAIN'],
            'COLLEGE OF AGRICULTURE' => [
                'AGRIBUSINESS MANAGEMENT DEPARMENT',
                'AGRICULTURAL ECONOMICS DEPARTMENT',
                'AGRICULTURAL EDUCATION EXTENSION',
                'AGRICULTURAL EDUCATION EXTENSION - PROJECT CLIMB',
                'ANIMAL SCIENCE - PCAARRD - DAIRY CATTLE PROJECT',
                'ANIMAL SCIENCE - PCAARRD - HALAL GOAT',
                'ANIMAL SCIENCE - SWINE SEMEN AND A.I. LABORATORY',
                'ANIMAL SCIENCE DEPARTMENT',
                'DEAN',
                'DEPARTMENT OF AGRONOMY AND PLANTBREEDING',
                'DEPARTMENT OF HORTICULTURE',
                'DEPARTMENT OF SOIL SCIENCE',
                'DEVELOPMENT COMMUNICATION DEPARTMENT',
                'ENTOMOLOGY DEPARTMENT',
                'MAIN',
                'PLANT PATHOLOGY DEPARTMENT',
                'READING ROOM',
                'REGISTRAR OFFICE',
                'SARAI',
                'STOREKEEPERS OFFICE',
                'SWINE SEMEN PROCESSING AND ARTIFICIAL INSEMINATION CENTER',
                'TISSUE CULTURE LABORATORY',
            ],
            'COLLEGE OF ARTS AND SCIENCE' => [
                'BEHAVIORAL SCIENCE DEPARTMENT',
                'BIOLOGY DEPARTMENT',
                'CHEMISTRY DEPARTMENT',
                'DEPARTMENT OF LANGUAGES AND LITERATURE',
                'MAIN',
                'MATH DEPARTMENT',
                'PHYSICS DEPARTMENT',
                'RESEARCH COMMITTEE',
                'SOCIAL SCIENCE DEPARTMENT',
            ],
            'COLLEGE OF BUSINESS AND MANAGEMENT' => [
                'ACCOUNTANCY DEPARTMENT',
                'BUSINESS ADMINITRATION DEPARTMENT',
                'DEPARTMENT OF ACCOUNTANCY',
                'MAIN',
                'OFFICE ADMINISTRATION DEPARTMENT',
            ],
            'COLLEGE OF EDUCATION' => [
                'COLLEGE SECRETARY',
                'LANGUAGE EDUCATION',
                'MAIN',
                'PROFESSIONAL EDUCATION',
                'SCIENCE EDUCATION DEPARTMENT',
                'SENIOR HIGH SCHOOL',
                'SUPPLY OFFICE',
            ],
            'COLLEGE OF ENGINEERING' => [
                'AGRICULTURAL AND BIOSYSTEMS ENGINEERING DEPARTMENT',
                'CIVIL ENGINEERING DEPARTMENT',
                'DEAN',
                'EF 0070',
                'ELECTRICAL ENGINEERING DEPARTMENT',
                'MAIN',
                'MECHANICAL ENGINEERING',
            ],
            'COLLEGE OF FORESTRY AND ENVIRONMENTAL SCIENCE' => [
                'ADMIN',
                'BAMBOO NICER',
                'BAMBOO PROJECT',
                'CHED-NAFES FALCATA',
                'CONSERVATION AND MASS PRODUCTION AT HIGH - YIELDING FALCATA SEED SOURCES IN MINDANAO RESEARCH',
                'FOREST BIOLOGICAL SCIENCE',
                'GEOSAFER',
                'IPDM',
                'MAIN',
            ],
            'COLLEGE OF HUMAN ECOLOGY' => [
                'COLLEGE REGISTRAR',
                'FOOD RESEARCH AND DEVELOPMENT (FRDC)',
                'FOOD SCIENCE',
                'HOME ECONOMICS EDUCATION AND FAMILY LIFE',
                'HOSPITAL MANAGEMENT',
                'MAIN',
                'NUTRITION AND DIETETICS',
                'TESDA',
            ],
            'COLLEGE OF NURSING' => ['MAIN', 'MARAWI SIEGE - PCHRD - DOST FUND'],
            'COLLEGE OF INFORMATION SCIENCES AND COMPUTING' => ['Information Technology'],
            'COLLEGE OF VETERINARY MEDICINE' => [
                'COLLEGE REGISTRAR',
                'DEAN',
                'DEPARTMENT OF ANATOMY PHYSIOLOGY AND PHARMACOLOGY',
                'DEPARTMENT OF MEDICINE SURGERY AND ZOOTECHNICS',
                'DEPARTMENT OF MICROBIOLOGY PATHOLOGY PARASITOLOGY AND PUBLIC HEALTH',
                'MAIN',
                'PROJECT HALAL',
                'VIRAL DISEASE PROJECT',
            ],
            'COMMISSION OF AUDIT' => ['MAIN'],
            'DATA PRIVACY OFFICE' => ['MAIN'],
            'DISASTER RISK REDUCTION MANAGEMENT OFFICE' => ['MAIN'],
            'DOST' => ['CMU AGRI - AQUA TECHNOLOGY BUSINESS INCUBATOR PROJECT'],
            'ENTERPRISE MANAGEMENT OFFICE (EMO)' => ['MAIN'],
            'GENERAL SERVICES' => ['MAIN'],
            'GUIDANCE COUNSELING CENTER' => ['MAIN'],
            'HOSPITALITY SERVICES AND FOOD ENTERPRISE OFFICEUIGP' => ['MAIN'],
            'HUMAN RESOURCE MANAGEMENT OFFICE' => ['BENEFITS', 'LEARNING AND DEVELOPMENT', 'LEAVE', 'MAIN', 'RECRUITMENT'],
            'INFORMATION AND COMMUNICATION UNIT (ICU)-EXTENSION' => ['MAIN'],
            'INSTITUTE OF COMPUTER APPLICATION' => ['MAIN'],
            'INTELLECTUAL PROPERTY AND TECHNOLOGY BUSINESS MANAGEMENT' => ['MAIN'],
            'INTERNAL AUDIT SERVICE' => ['MAIN'],
            'INTERNATIONAL RELATIONS OFFICE' => ['MAIN'],
            'LEAD DOCUMENT CONTROLLER' => ['MAIN'],
            'LEAD INTERNAL AUDITOR' => ['MAIN'],
            'NATURAL PRODUCT RESEARCH AND DEVELOPMENT CENTER (NPRDC)' => ['MAIN'],
            'NATURAL SCIENCE RESEARCH CENTER (NSRC)' => [
                'MAIN',
                'TUKLAS LUNAS DEVELOPMENT CENTER - PROJECT 1',
                'TUKLAS LUNAS DEVELOPMENT CENTER - PROJECT 2',
                'TUKLAS LUNAS DEVELOPMENT CENTER - PROJECT 3',
                'TUKLAS LUNAS DEVELOPMENT CENTER - PROJECT 4',
                'TUKLAS LUNAS DEVELOPMENT CENTER - PROJECT 5',
            ],
            'NORTHERN MINDANAO CONSORTIUM FOR AGRICULTURE AQUATIC AND NATURAL RESOURCES RESEARCH AND DEVELOPMENT (NOMCAARRD)' => ['MAIN'],
            'OFFICE OF ADMINISTRATIVE SERVICES' => ['MAIN'],
            'OFFICE OF ADMISSIONS SCHOLARSHIPS AND PLACEMENT' => ['MAIN'],
            'OFFICE OF ALUMNI RELATIONS AND LINKAGES' => ['MAIN'],
            'OFFICE OF DIGITAL TRANSFORMATION' => ['MAIN'],
            'OFFICE OF FINANCIAL MANAGEMENT SERVICE (OFMS)' => ['MAIN'],
            'OFFICE OF HEALTH SERVICES' => ['MAIN'],
            'OFFICE OF INSPECTORATE TEAM FOR SUPPLIES AND MATERIALS' => ['MAIN'],
            'OFFICE OF STUDENT AFFAIRS' => ['MAIN'],
            'OFFICE OF THE BRANDING' => ['MAIN'],
            'OFFICE OF THE DIRECTOR OF INSTRUCTION (DOI)' => ['MAIN'],
            'OFFICE OF THE NATIONAL SERVICE TRAINING PROGRAM (NSTP)' => ['MAIN'],
            'OFFICE OF THE PRESIDENT' => [
                'LEGAL OFFICE',
                'MAIN',
                'UNIVERSITY BOARD AND SECRETARY',
                'UNIVERSITY HOUSING COMMITTEE',
            ],
            'OFFICE OF THE UNIVERSITY REGISTRAR (OUR)' => ['MAIN'],
            'OFFICE OF THE VICE PRESIDENT FOR RESOURCE GENERATION AND MANAGEMENT OFFICE (VPRGMO)' => ['MAIN'],
            'OFFICE OF THE VICE-PRESIDENT FOR ADMINISTRATION (VPA)' => ['MAIN'],
            'OFFICE OF THE VICE-PRESIDENT FOR RESEARCH DEVELOPMENT AND EXTENSION (VPRDE)' => ['MAIN'],
            'OFFICE OF THE VICE-PRESIDENT FOR THE ACADEMIC AFFAIRS (VPAA)' => ['MAIN'],
            'PHYSICAL EDUCATION DEPARTMENT' => ['MAIN'],
            'PROJECT IMPLEMENTING UNIT' => ['MAIN'],
            'PUBLIC RELATIONS AND INFORMATION OFFICE' => ['MAIN'],
            'QUACQUARELLI SAYMONDS' => ['MAIN'],
            'QUALITY ASSURANCE' => ['MAIN'],
            'RECORDS MANAGEMENT UNIT (RMU)' => ['MAIN'],
            'RESEARCH OFFICE' => ['MAIN'],
            'RESOURCE GENERATION AND MANAGEMENT OFFICE (RGMO)' => [
                'CROPS',
                'FOREST RESOURCE ENTERPRISE OFFICE (FREO)',
                'LIVESTOCK',
                'MAIN',
                'RUBBER',
                'SUPPLY AND MATERIALS',
                'SUPPORT SERVICES',
            ],
            'SECURITY SERVICES UNIT' => ['MAIN'],
            'SOCIO-CULTURAL' => ['MAIN'],
            'SPECIAL MAINTENANCE AND BEAUTIFICATION COMMITTEE (SMBC)' => ['MAIN'],
            'SUPPLY AND PROPERTY MANAGEMENT UNIT' => ['MAIN'],
            'TECHNO DEMO SERVICES UNIT' => ['MAIN'],
            'UNIVERSITY CENTER FOR GENDER AND DEVELOPMENT' => ['MAIN'],
            'UNIVERSITY EXTENSION OFFICE' => ['MAIN'],
            'UNIVERSITY HOMESTAY' => ['MAIN'],
            'UNIVERSITY HOSPITAL' => ['MAIN'],
            'UNIVERSITY LABORATORY HIGH SCHOOL' => ['MAIN'],
            'UNIVERSITY LIBRARY' => ['MAIN'],
            'UNIVERSITY PLANNING AND DEVELOPMENT OFFICE' => ['MAIN'],
            'VALUE ENGINEERING AND VALUE ANALYSIS COMMITTEE' => ['MAIN'],
        ];
    }
}
